# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Workflow deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: setup yarn
      run: npm install -g yarn pm2

    - name: Build,Start and Restart Web Application
      run: rm -rf node_modules && yarn build && pm2 start yarn -- start && pm2 restart yarn

    - name: build project
      run: npm run build --if-present

    - name: copy env var 
      run: |
        touch .env
        echo "{{ secrets.PROD_ENV_FILE }}" > .env
